trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'
  JDK_VERSION: '11'
  
- script: |
    # Install Google Chrome
    if [ ! -f /usr/bin/google-chrome ]; then
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo apt-get update
      sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
    fi
  displayName: 'Install Google Chrome'

- script: |
    # Remove old ChromeDriver if it exists
    if [ -f /usr/local/bin/chromedriver ]; then
      sudo rm /usr/local/bin/chromedriver
    fi

    # Fetch the installed Chrome version (major version only)
    CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+')

    # Fetch the appropriate ChromeDriver version for the installed Chrome version
    CHROME_DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")

    if [ -z "$CHROME_DRIVER_VERSION" ]; then
      echo "Could not find ChromeDriver version for Chrome version ${CHROME_VERSION}"
      exit 1
    fi

    # Download and install the correct ChromeDriver
    wget -N https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo mv -f chromedriver /usr/local/bin/chromedriver
    sudo chmod +x /usr/local/bin/chromedriver
  displayName: 'Remove old ChromeDriver and Install New ChromeDriver'

- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    options: 'clean test -DSuiteXmlFile=suitefiles/PulseSuite.xml'
  displayName: 'Run Maven Tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/cucumber-reports'
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'
