trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'
  JDK_VERSION: '11'
  CHROME_VERSION: '114.0.5735.90'  # Specify the version compatible with your ChromeDriver

steps:
- script: |
    # Check if Java JDK is already installed
    if ! java -version 2>&1 | grep -q 'openjdk version "11'; then
      echo "Java JDK 11 not found. Installing..."
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk wget unzip
    else
      echo "Java JDK 11 is already installed."
    fi
  displayName: 'Check and Install Java JDK'

- script: |
    # Remove any existing Google Chrome installation
    sudo apt-get remove -y google-chrome-stable
    
    # Install specific version of Google Chrome
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo apt-get update
    sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
    sudo apt-get install -y --allow-downgrades google-chrome-stable=${CHROME_VERSION}-1
  displayName: 'Downgrade Google Chrome'

- script: |
    # Remove old ChromeDriver if it exists
    if [ -f /usr/local/bin/chromedriver ]; then
      sudo rm /usr/local/bin/chromedriver
    fi

    # Download and install the correct ChromeDriver for Chrome version 114
    CHROME_DRIVER_VERSION="114.0.5735.90"  # Replace this with the exact version if necessary
    wget -N https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo mv -f chromedriver /usr/local/bin/chromedriver
    sudo chmod +x /usr/local/bin/chromedriver
  displayName: 'Install ChromeDriver'

- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    options: 'clean test -DSuiteXmlFile=suitefiles/PulseSuite.xml'
  displayName: 'Run Maven Tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/cucumber-reports'
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'
