trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'
  JDK_VERSION: '11'

steps:
- script: |
    # Check if Java JDK is already installed
    if (-not (Get-Command "java" -ErrorAction SilentlyContinue)) {
        Write-Output "Java JDK 11 not found. Installing..."
        choco install -y openjdk11
    } else {
        Write-Output "Java JDK 11 is already installed."
    }
  displayName: 'Check and Install Java JDK'

- script: |
    # Install Google Chrome if not already installed
    if (-not (Get-Command "chrome" -ErrorAction SilentlyContinue)) {
        Write-Output "Google Chrome not found. Installing..."
        choco install -y googlechrome
    } else {
        Write-Output "Google Chrome is already installed."
    }
  displayName: 'Install Google Chrome'

- script: |
    # Verify ChromeDriver installation
    $chromeDriverPath = "C:\tools\chromedriver\chromedriver.exe"
    if (Test-Path $chromeDriverPath) {
        Write-Output "ChromeDriver is already installed at $chromeDriverPath"
    } else {
        Write-Output "ChromeDriver not found. Please check the installation."
        exit 1
    }
  displayName: 'Verify ChromeDriver Installation'

- script: |
    # Run a simple test to ensure Java, Chrome, and ChromeDriver are installed correctly
    java -version
    chrome --version
    & C:\tools\chromedriver\chromedriver.exe --version
  displayName: 'Verify Installations'

- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    options: 'clean test -DSuiteXmlFile=suitefiles/PulseSuite.xml'
  displayName: 'Run Maven Tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/cucumber-reports'  # Ensure this path is correct for your Cucumber reports
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'
  condition: succeeded()
