trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'
  JDK_VERSION: '11'

steps:
- script: |
    # Check if Java JDK is already installed
    if ! java -version 2>&1 | grep -q 'openjdk version "11'; then
      echo "Java JDK 11 not found. Installing..."
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk wget unzip
    else
      echo "Java JDK 11 is already installed."
    fi
  displayName: 'Check and Install Java JDK'

- script: |
    # Install Google Chrome version 127
    echo "Installing Google Chrome version 127..."
    wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_127.0.6533.88-1_amd64.deb
    sudo dpkg -i google-chrome-stable_127.0.6533.88-1_amd64.deb
    sudo apt-get -f install -y
  displayName: 'Install Google Chrome Version 127'

- script: |
    # Install ChromeDriver version 114
    echo "Installing ChromeDriver version 114..."
    wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo mv chromedriver /usr/local/bin/chromedriver
    sudo chmod +x /usr/local/bin/chromedriver
  displayName: 'Install ChromeDriver Version 114'

- script: |
    # Print Google Chrome and ChromeDriver versions
    echo "Google Chrome version: $(google-chrome --version)"
    echo "ChromeDriver version: $(chromedriver --version)"
  displayName: 'Print Google Chrome and ChromeDriver Versions'

- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    options: 'clean test -DSuiteXmlFile=suitefiles/PulseSuite.xml'
  displayName: 'Run Maven Tests'

- script: |
    if [ ! -d 'target/cucumber-reports' ]; then
      echo "Cucumber reports directory not found. Exiting..."
      exit 1
    fi
  displayName: 'Check Cucumber Reports Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/cucumber-reports'
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'
  condition: succeeded()
