trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'
  JDK_VERSION: '11'

steps:
- script: |
    # Check if Java JDK is already installed
    if ! java -version 2>&1 | grep -q 'openjdk version "11'; then
      echo "Java JDK 11 not found. Installing..."
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk wget unzip
    else
      echo "Java JDK 11 is already installed."
    fi
  displayName: 'Check and Install Java JDK'

- script: |
    # Install Google Chrome if not already installed
    if [ ! -f /usr/bin/google-chrome ]; then
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo apt-get update
      sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
    else
      echo "Google Chrome is already installed."
    fi
  displayName: 'Install Google Chrome'

- script: |
    # Remove existing ChromeDriver if present
    if [ -f /usr/local/bin/chromedriver ]; then
      echo "Removing existing ChromeDriver..."
      sudo rm -f /usr/local/bin/chromedriver
    else
      echo "No existing ChromeDriver found."
    fi

    # Download and install ChromeDriver for Chrome version 127
    echo "Installing ChromeDriver for Chrome 127..."
    wget https://chromedriver.storage.googleapis.com/127.0.6533.87/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo mv chromedriver /usr/local/bin/chromedriver
    sudo chmod +x /usr/local/bin/chromedriver
  displayName: 'Install ChromeDriver for Chrome 127'

- script: |
    # Run a simple curl command to test network connectivity
    echo "Testing network connectivity..."
    curl -I https://www.google.com
  displayName: 'Test Network Connectivity'

- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    options: 'clean test -DSuiteXmlFile=suitefiles/PulseSuite.xml'
  displayName: 'Run Maven Tests'

- script: |
    if [ ! -d 'target/cucumber-reports' ]; then
      echo "Cucumber reports directory not found. Exiting..."
      exit 1
    fi
  displayName: 'Check Cucumber Reports Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/cucumber-reports'  # Ensure this path is correct for your Cucumber reports
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'
  condition: succeeded()
