trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'
  JDK_VERSION: '11'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jdk wget unzip
  displayName: 'Install Java JDK'

- script: |
    # Install Google Chrome
    if [ ! -f /usr/bin/google-chrome ]; then
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo apt-get update
      sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
    fi
  displayName: 'Install Google Chrome'

- script: |
    # Remove old ChromeDriver if it exists
    if [ -f /usr/local/bin/chromedriver ]; then
      sudo rm -f /usr/local/bin/chromedriver
    fi

    # Install ChromeDriver for Chrome version 127
    wget https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.99/linux64/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo mv -f chromedriver /usr/local/bin/chromedriver
    sudo chmod +x /usr/local/bin/chromedriver
  displayName: 'Remove old ChromeDriver and Install New ChromeDriver'

- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    options: 'clean test -DSuiteXmlFile=suitefiles/PulseSuite.xml'
  displayName: 'Run Maven Tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/cucumber-reports'
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'
