trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'
  JDK_VERSION: '11'
  CHROME_VERSION: '113.0.5672.126'
  CHROMEDRIVER_VERSION: '113.0.5672.126'

steps:
- script: |
    # Check if Java JDK is already installed
    if ! java -version 2>&1 | grep -q 'openjdk version "11'; then
      echo "Java JDK 11 not found. Installing..."
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jdk wget unzip
    else
      echo "Java JDK 11 is already installed."
    fi
  displayName: 'Check and Install Java JDK'

- script: |
    # Uninstall existing Google Chrome and ChromeDriver
    if [ -f /usr/bin/google-chrome ]; then
      echo "Removing existing Google Chrome..."
      sudo apt-get remove -y google-chrome-stable
    fi
    if [ -f /usr/local/bin/chromedriver ]; then
      echo "Removing existing ChromeDriver..."
      sudo rm -f /usr/local/bin/chromedriver
    fi
  displayName: 'Uninstall Existing Google Chrome and ChromeDriver'

- script: |
    # Install Google Chrome version 113
    echo "Installing Google Chrome version 113..."
    wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_113.0.5672.126-1_amd64.deb
    sudo apt-get update
    sudo apt-get install -y ./google-chrome-stable_113.0.5672.126-1_amd64.deb
  displayName: 'Install Google Chrome Version 113'

- script: |
    # Install ChromeDriver version 113
    echo "Installing ChromeDriver version 113..."
    wget https://chromedriver.storage.googleapis.com/113.0.5672.126/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo mv -f chromedriver /usr/local/bin/chromedriver
    sudo chmod +x /usr/local/bin/chromedriver
    rm chromedriver_linux64.zip
  displayName: 'Install ChromeDriver Version 113'

- script: |
    # Print versions of Google Chrome and ChromeDriver
    echo "Google Chrome version:"
    google-chrome --version
    echo "ChromeDriver version:"
    chromedriver --version
  displayName: 'Print Google Chrome and ChromeDriver Versions'

- script: |
    # Run a simple curl command to test network connectivity
    echo "Testing network connectivity..."
    curl -I https://www.google.com
  displayName: 'Test Network Connectivity'

- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    options: 'clean test -DSuiteXmlFile=suitefiles/PulseSuite.xml'
  displayName: 'Run Maven Tests'

- script: |
    if [ ! -d 'target/cucumber-reports' ]; then
      echo "Cucumber reports directory not found. Exiting..."
      exit 1
    fi
  displayName: 'Check Cucumber Reports Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/cucumber-reports'  # Ensure this path is correct for your Cucumber reports
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'
  condition: succeeded()
