trigger:
- main

pool:
  vmImage: 'windows-2019'

variables:
  MAVEN_OPTS: '-Xmx1024m'
  JDK_VERSION: '11'

steps:

- script: |
    # Verify Google Chrome installation
    if (Test-Path "C:\Program Files\Google\Chrome\Application\chrome.exe") {
      Write-Host "Google Chrome is already installed."
    } else {
      Write-Host "Google Chrome not found. Installing..."
      choco install googlechrome -y
    }
  displayName: 'Verify Google Chrome Installation'

- script: |
    # Verify ChromeDriver installation
    if (Test-Path "C:\tools\chromedriver\chromedriver.exe") {
      Write-Host "ChromeDriver is already installed."
    } else {
      Write-Host "ChromeDriver not found. Installing..."
      New-Item -ItemType Directory -Force -Path "C:\tools\chromedriver"
      Invoke-WebRequest -Uri https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.99/win64/chromedriver-win64.zip -OutFile chromedriver-win64.zip
      Expand-Archive -Path chromedriver-win64.zip -DestinationPath "C:\tools\chromedriver"
    }
  displayName: 'Verify ChromeDriver Installation'

- script: |
    # Run a simple ping command to test network connectivity
    Write-Host "Testing network connectivity..."
    ping www.google.com
  displayName: 'Test Network Connectivity'

- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    options: 'clean test -DSuiteXmlFile=suitefiles/PulseSuite.xml'
  displayName: 'Run Maven Tests'

- script: |
    if (!(Test-Path 'target\cucumber-reports')) {
      Write-Host "Cucumber reports directory not found. Exiting..."
      exit 1
    }
  displayName: 'Check Cucumber Reports Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target\cucumber-reports'  # Ensure this path is correct for your Cucumber reports
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'
  condition: succeeded()
