trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'

steps:
- task: UseMaven@1
  inputs:
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false

- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jdk wget unzip

- script: |
    # Install Google Chrome
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo apt-get update
    sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
  displayName: 'Install Google Chrome'

- script: |
    # Install ChromeDriver
    CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
    wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    sudo mv -f chromedriver /usr/local/bin/chromedriver
    sudo chmod +x /usr/local/bin/chromedriver
  displayName: 'Install ChromeDriver'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test -DSuiteXmlFile=suitefiles/PulseSuite.xml'
    options: '-DskipTests=false'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    mavenOptions: '-Xmx3072m'
  displayName: 'Run Tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/cucumber-reports/Cucumber.json'
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'
