trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: '-Xmx1024m'
  JDK_VERSION: '11'

steps:
- script: |
    # Install Java JDK
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jdk wget unzip
  displayName: 'Install Java JDK'

- script: |
    # Install Google Chrome
    if [ ! -f /usr/bin/google-chrome ]; then
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo apt-get update
      sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
    fi
  displayName: 'Install Google Chrome'

- script: |
    # Install ChromeDriver
    if [ ! -f /usr/local/bin/chromedriver ]; then
      CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
      wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      sudo mv -f chromedriver /usr/local/bin/chromedriver
      sudo chmod +x /usr/local/bin/chromedriver
    fi
  displayName: 'Install ChromeDriver'

- task: Maven@3
  inputs:
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    options: 'clean test -DSuiteXmlFile=suitefiles/PulseSuite.xml'
  displayName: 'Run Maven Tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'target/cucumber-reports'
    artifactName: 'cucumber-reports'
    publishLocation: 'Container'
  displayName: 'Publish Cucumber Reports'
